config/routes.rb
Rails.application.routes.draw do

  get 'my_proposals/view'

  devise_for :users
  get 'stats/view/:proposal_id' => 'stats#view', as: :stats_view

  get 'welcome/index'

  post 'proposals/email'

  get '/proposals/new'
  post '/proposals/new' => 'proposals#create'
  post '/proposals' => 'proposals#create'
  get '/proposals/:proposal_id' => 'proposals#show', as: :show_proposal

  get '/proposals/:id/edit(.:format)' => 'proposals#edit', as: :edit_proposal

  delete '/proposals/:id(.:format)' => 'proposals#destroy', as: :delete_proposal

  post 'vote/vote'
  get '/vote/show/:proposal_id' => 'vote#show', as: :vote

  root 'welcome#index'

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :user

  has_many :voters

  validates :title, :details, :email, presence: true
  validates :proposal_id, uniqueness: true

  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/


  after_initialize :init

  def init
    if self.new_record?
    # create a random string to identify this record, ONLY if brand new record
      self.proposal_id = create_random_id
      self.total_yes = 0
      self.total_maybe = 0
      self.total_no = 0
    end
  end

  def create_random_id

    all_letters = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten

    sixteen_characters = (0...16).map { all_letters[rand(all_letters.length)] }.join

    sixteen_characters
  end

  def voting_url
    "/vote/show/" + proposal_id
  end

  def stats_url
    "/stats/view/" + proposal_id
  end

  def proposal_url
    "/proposals/" + proposal_id
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :proposals

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  belongs_to :proposal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_proposals_controller.rb
class MyProposalsController < ApplicationController
  def view
    # todo check if logged in?
    @proposals = current_user.proposals


  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  #before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  # GET /proposals.json
  #def index
  #  @proposals = Proposal.all
  #end

  # GET /proposals/:proposal_id
  # GET /proposals/1.json
  def show
    proposal_id = params[:proposal_id]
    @proposal = Proposal.find_by(proposal_id: proposal_id)
  end


  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
    proposal_id = params[:proposal_id]
    @proposal = Proposal.find_by(proposal_id: proposal_id)
  end

  # POST /proposals
  # POST /proposals.json
  def create

    if user_signed_in?
      @proposal = current_user.proposals.create(proposal_params)
    else
      @proposal = Proposal.new(proposal_params)
    end

    respond_to do |format|
      if @proposal.save

        # todo is this next used?
        @email = ''

        # send an email confirming the proposal was created
        ProposalMailer.proposal_email(@proposal).deliver

        format.html { redirect_to controller: 'proposals', action: 'show', proposal_id: @proposal.proposal_id }
        format.json { redirect_to action: 'show', status: :created, location: @proposal }
      else
        format.html { render action: 'new' }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @proposal }
      else
        format.html { render action: 'edit' }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm

  end


  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end


  def email

    respond_to do |format|
      permitted_params = params.permit(:invitee_email, :id)

      invite_email = permitted_params[:invitee_email]
      id = permitted_params[:id]

      @proposal = Proposal.find(id)
      @voter = @proposal.voters.create
      @voter.email = invite_email
      if @voter.save

        # send an invite email
        AddVoterMailer.add_voter_email(@voter, @proposal).deliver

        format.js
        format.json
      end

    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  #def set_proposal
    #@proposal = Proposal.find(params[:id])
  #end

  # Never trust parameters from the scary internet, only allow the white list through.
  def proposal_params
    params.require(:proposal).permit(:title, :details, :email, :name, :proposal_id, :total_yes, :total_maybe, :total_no)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def view
    proposal_id = params[:proposal_id]
    @proposal = Proposal.find_by(proposal_id: proposal_id)
    @voters = @proposal.voters
  end

end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  def vote
    proposal_id = params[:proposal_id]
    @proposal = Proposal.find_by(proposal_id: proposal_id)

    @vote = params[:choice]

    if @vote.eql? "Yes"
      @proposal.total_yes += 1
      @proposal.save
    end

    if @vote.eql? "No"
      @proposal.total_no += 1
      @proposal.save
    end

    if @vote.eql? "Maybe"
      @proposal.total_maybe += 1
      @proposal.save
    end

    @voter = @proposal.voters.create

    permitted_params = params.permit(:vote_email, :vote_name)
    # todo not sure why we are filtering with params.permit, since we access them by the same key below

    @voter.email = permitted_params[:vote_email]
    @voter.name = permitted_params[:vote_name]
    @voter.vote = @vote.downcase

    if @voter.save

      # send an email confirming the proposal was created
      NewVoteMailer.vote_email(@proposal).deliver

    end
  # todo handle error on save

  end

  def show
    @proposal = Proposal.find_by(proposal_id: params[:proposal_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_proposals_helper.rb
module MyProposalsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DeciderApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="//netdpowerna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

  <!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <style type="text/css">
      /* Sticky footer styles
-------------------------------------------------- */

      html,
      body {
          height: 100%;
          /* The html and body elements cannot have any padding or margin. */
      }

      /* Wrapper for page content to push down footer */
      #wrap {
          min-height: 100%;
          height: auto !important;
          height: 100%;
          /* Negative indent footer by its height */
          margin: 0 auto -60px;
          /* Pad bottom by footer height */
          padding: 0 0 60px;
      }

      /* Set the fixed height of the footer here */
      #footer {
          height: 60px;
          background-color: #f5f5f5;
      }

      /* Custom page CSS
      -------------------------------------------------- */
      /* Not required for template or sticky footer method. */

      #wrap > .container {
          padding: 60px 15px 0;
      }

      .container .credit {
          margin: 20px 0;
      }

      #footer > .container {
          padding-left: 15px;
          padding-right: 15px;
      }

      code {
          font-size: 80%;
      }
  </style>


</head>
<body>

<!-- Wrap all page content here -->
<div id="wrap">

  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Let's Decide</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <!--<li><a href="#about">About</a></li>-->
          <!--<li><a href="#contact">Contact</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li class="active"><a href="#">Logged in as <strong><%= current_user.email %></strong></a></li>
              <li class="active"><%= link_to 'My Proposals', my_proposals_view_path, id: "view__my_proposals" %></li>
              <li class="active"><%= link_to 'Edit profile', edit_user_registration_path, id: "edit_profile" %></li>
              <li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete, id: "logout" %></li>
          <% else %>
            <li class="active"><%= link_to "Sign up", new_user_registration_path, id: "signup" %></li>
            <li class="active"><%= link_to "Sign in", new_user_session_path, id: "signin" %></li>
          <% end %>
        </ul>

      </div>
      <!--/.nav-collapse -->
    </div>
  </div>

  <!-- Begin page content -->
  <div class="container">

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>
</div>



<div id="footer">
  <div class="container">
    <p class="text-muted credit">Let's Decide is a project by <a href="http://www.leanintuit.com" target="_blank">Leanintuit</a>.</p>
  </div>
</div>


<script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<script type='text/javascript' src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


<!-- JavaScript jQuery code from Bootply.com editor -->

<script type='text/javascript'>

    $(document).ready(function () {


    });

</script>

</body>
</html>

app/views/my_proposals/view.html.erb
<h1>List Of My Proposals</h1>

<% if @proposals.empty? %>
  <b>You have not created any proposals yet</b>
<% else %>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Details</th>
          <th>Date Created</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @proposals.each_with_index do |proposal, proposal_count | %>
          <% proposal_count += 1 %>
          <tr>
            <td><%= link_to proposal.title, show_proposal_path(proposal.proposal_id), id: 'proposal_link_' + proposal_count.to_s %></td>
            <td><%= proposal.details %></td>
            <td><%= proposal.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

<% end %>

<br>

app/views/proposals/_form.html.erb
<%= form_for @proposal, url: proposals_path do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <br>
    <div class="field">
    <%= f.label :title, 'I propose that:' %><br>
    <%= f.text_field :title, size: "60" %>
  </div>
  <div class="field">
    <%= f.label :details, 'Details of what you are proposing' %><br>
    <%= f.text_area :details, size: "60x6" %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :value => user_signed_in? ? current_user.email : 'xxx' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :id => "create_proposal" %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %>

app/views/proposals/email.js.erb
$("#addEmail").append('<p>request sent to email:<%= escape_javascript(@voter.email) %></p>')

app/views/proposals/index.html.erb
<h1>Listing proposals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Details</th>
      <th>Proposal ID</th>
      <th>Total yes</th>
      <th>Total maybe</th>
      <th>Total no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.title %></td>
        <td><%= proposal.details %></td>
        <td><%= proposal.proposal_id %></td>
        <td><%= proposal.email %></td>
        <td><%= proposal.total_yes %></td>
        <td><%= proposal.total_maybe %></td>
        <td><%= proposal.total_no %></td>
        <td><%= link_to 'Show', proposal %></td>
        <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposal', new_proposal_path %>

app/views/proposals/new.html.erb
<H2>Make a proposal</H2>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p><h4>Your Proposal</h4></p>

<br>
<p>
  <strong>You propose that:</strong>
  <%= @proposal.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @proposal.details %>
</p>

<p>
  <strong>Your name:</strong>
  <%= @proposal.name %>
</p>

<p>
  <strong>Your email:</strong>
  <%= @proposal.email %>
</p>

<p>An email has been sent to you with these details.</p>

<br>
<p>In order for people to vote on this proposal you have two choices.<br>
  1) Send them this link: <%= voting_path = vote_path(@proposal.proposal_id, :only_path => false)
                              link_to voting_path, voting_path, id: "vote_url" %>

  <br>
  2) Add their email below. An email with the link will be sent to them.
  <br>

  <%= form_tag('/proposals/email', :id => 'addEmail', remote: true) do %>

      <%= hidden_field_tag(:id, @proposal.id) %>

      <%= label_tag(:invitee_email, 'Send this proposal to: ') %>
      <%= text_field_tag 'invitee_email', nil, placeholder: 'enter email to invite' %>

      <%= button_tag "Send Invite", :data => { :disable_with => "Sending email...." } %>

  <% end %>
</p>

<p>In order to check on the vote use the following link:
  <%= stats_viewing_path = stats_view_path(@proposal.proposal_id, :only_path => false)
                                            link_to stats_viewing_path, stats_viewing_path, id: "stats_url" %>
</p>

app/views/stats/view.html.erb
<p><h2>Stats for proposal:<%=@proposal.title%></h2></p>

<p>Current votes:</p>
<p>Yes: <%=@proposal.total_yes%>  vote(s)</p>
<p>Maybe: <%=@proposal.total_maybe%> vote(s)</p>
<p>No: <%=@proposal.total_no%> vote(s)</p>

<p>People who voted:</p>
<% @voters.each do |voter| %>
    <p><%= voter.name %> : <%= voter.email %> : <%= voter.vote %></p>
<% end %>

app/views/vote/show.html.erb
<h1>Vote on a proposal</h1>

<p>Please place your vote for the following proposal</p>
<p>Proposal Title: <%= @proposal.title %> </p>
<p>Proposal Details: <%=@proposal.details%></p>
<p>Proposed by: <%=@proposal.name%></p>

<%= form_tag("/vote/vote") do %>

    <%= hidden_field_tag(:proposal_id, @proposal.proposal_id) %>

    <p><%= radio_button_tag(:choice, 'Yes') %>
      <%= label_tag(:choice_Yes, 'Yes') %>
    </p>

    <p><%= radio_button_tag(:choice, 'No') %>
      <%= label_tag(:choice_No, 'No') %>
    </p>

    <p><%= radio_button_tag(:choice, 'Maybe') %>
      <%= label_tag(:choice_Maybe, 'Maybe') %>
    </p>

    <div class="field">
      <%= label_tag :vote_name, 'name:' %>
      <br>
      <%= text_field_tag :vote_name, nil, placeholder:  'your name' %>
    </div>

    <div class="field">
      <%= label_tag :vote_email, 'email:' %>
      <br>
      <%= email_field_tag :vote_email, nil, placeholder: current_user.nil? ? 'you@someplace.com' : current_user.email %>
    </div>

    <p><%= submit_tag "Vote!", :id => 'vote_submit' %></p>


<% end %>

app/views/vote/vote.html.erb
Vote registered.

You choose: <%= @vote%>

<p>Current votes:</p>
<p>Yes: <%=@proposal.total_yes%>  vote(s)</p>
<p>Maybe: <%=@proposal.total_maybe%> vote(s)</p>
<p>No: <%=@proposal.total_no%> vote(s)</p>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>Welcome to Let's Decide</h1>
</div>

<p class="lead">Decide on something using the Decider Protocol from Jim and Michele McCarthy's <a href="http://www.mccarthyshow.com/online/">Core Protocols</a>.</p>


<p><h4><%= link_to 'Click Here To Create a proposal', proposals_new_path, id: 'proposal_create', class: 'actionButton'%></h4></p>